---
title: "First-post"
description: |
  A short description of the post.
author:
  - name: Michelle Cui
  - url: {file:///Users/michellecui/Library/CloudStorage/OneDrive-UniversityOfOregon/2024%20Winter/edld_652_data_viz/edld-652-blog/_posts/2025-02-19-first-post/first-post.html}
date: 2025-02-19
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Check this amazing plot I made with ggplot.

```{r include=FALSE}
library(tidyverse)
library(here)
library(scales)
library(ggforce)
library(ggrepel)
library(gghighlight)
library(ggplot2)
library(dplyr)
library(forcats)
library(maps)
library(scales)
library(colorblindr)
library(patchwork)
library(plotly) # adds some interactivity to the plot
theme_set(theme_minimal(base_family = "Times"))
```

```{r include=FALSE}
honey <- read.csv(here("data","honeyproduction.csv"))
```

```{r}
honey_98_12 <- honey %>% 
  filter(year == 1998 | year == 2012) %>% 
  select(state, year, stocks) %>% 
  mutate(state = fct_reorder(state, stocks))

p1 <- ggplot(honey_98_12, aes(x = state, y = stocks, fill = year)) +
  geom_col(position = "dodge") +
  labs(title = "Honey Stocks by State in 1998 vs 2012",
       x = "State",
       y = "Honey Stocks",
       fill = "Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 5))+
  scale_y_continuous(labels = label_comma())

p1
```

