---
title: "Michelle Cui's Final Project"
description: |
  This is a blog where I am building up my work for EDLD 652 Data Visualization Final Project. The dataset I am looking at is the International Computer and Information Literacy Study (ICILS) Teacher Panel 2020. The dataset was retrieved from the International Association for the Evaluation of Educational Achievement (IEA) that is the host orgranization of ICILS. Here is more information about the study and report: [Data](https://www.iea.nl/data-tools/repository/icils),  [ICILS](https://nces.ed.gov/surveys/icils/), [Report: Changes in Digital Learning During a Pandemic—Findings From the ICILS](https://www.iea.nl/publications/study-reports/international-reports-iea-studies/changes-digital-learning-during Teacher Panel)
categories:
  - Education Techonology
author:
  - name: Michelle Cui
date: 2025-02-19
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r message = FALSE, warning = FALSE, include=FALSE}
library(here)
library(rio)
library(tidyverse)
library(janitor)
library(haven)
library(dplyr)
library(gt)
library(kableExtra)
library(scales)
library(colorblindr)
library(patchwork)
library(plotly) # adds some interactivity to the plot
theme_set(theme_minimal(base_family = "Times"))
```

```{r include=FALSE, message=FALSE}
load(here("data","MERGEDTP.Rdata"))
mergedtp <- MERGEDTP
```

#### Research question one

```{r message=FALSE, warning=FALSE, include=FALSE}
rq1 <- mergedtp %>% 
  clean_names() %>% 
  select(idteach,cntry,year,partt,it2g14a,it2g05a, it2g05b, ii2g11f)

sum(is.na(rq1))
colSums(is.na(rq1))

rq1_clean <- rq1 %>% 
  filter(!is.na(idteach) &!is.na(partt))

```

```{r message=FALSE, warning=FALSE, include=FALSE}
rq1_missing <- rq1_clean %>% 
  select(-c(1:4)) %>% 
  summarise(across(everything(), ~sum(is.na(.)))) %>% 
  rename(`School Consider ICT a Priority`=it2g14a,
         `ICT Use During Lesson` = it2g05a,
         `ICT Prepare Before Lesson` = it2g05b,
         `ICT Self-support` = ii2g11f) %>% 
  pivot_longer(everything(), 
               names_to = "Variable", 
               values_to = "Missing_Values")

rq1_missing %>% 
  gt() %>% 
  tab_header(
    title = "Table 1. Missing values in key ICT related variables",
    subtitle = "Insights into digital infrastructure and support disparities"
  )

rq1_table01 <- rq1_missing %>% 
  gt() %>% 
  tab_header(
    title = "Table 1. Missing values in key ICT related variables",
    subtitle = "Insights into digital infrastructure and support disparities"
  )
```

The final version of Table 1

```{r}
rq1_table01
```

```{r message=FALSE, warning=FALSE, include=FALSE}
rq1_clean$it2g14a <- factor(rq1_clean$it2g14a,
                            levels = c(1,2,3,4),
                            labels = c("Strongly agree",
                                       "Agree",
                                       "Disagree",
                                       "Strongly disagree"))

rq1_clean$it2g05a <- factor(rq1_clean$it2g05a,
                            levels = c(1,2,3,4),
                            labels = c("Never", "Less than two years", "Between two and five years", "More than five years"))

rq1_clean$it2g05b <- factor(rq1_clean$it2g05b,
                            levels = c(1,2,3,4),
                            labels = c("Never", "Less than two years", "Between two and five years", "More than five years"))

rq1_clean %>% 
  select(-c(1)) %>% 
  group_by(it2g14a) %>% 
  summarise(Mean_ICT_Lesson = mean(it2g05a, na.rm = TRUE),
            Mean_ICT_Prep = mean(it2g05b, na.rm = TRUE),
            Count = n())

table(rq1_clean$it2g14a)
```

QR1: Visualization

```{r}
rq1_clean <- filter(rq1_clean, !is.na(it2g14a)&!is.na(it2g05a))

p1 <- ggplot(data = rq1_clean, aes(x = it2g05a, fill= it2g14a)) +
  geom_bar(position = "dodge")+
  facet_wrap(~cntry)+
  labs(title = "Figure 1. Frequency of ICT Use during lessons by School ICT Priority across countries",
       x = "ICT Use During Lessons",
       y = "Count",
       fill = "School ICT Priority")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_fill_OkabeIto()

p1
```

Lab7 Tasks

- Set up git/github repo
- clean data for Research Question One
- Use distill to deploy a website
- Published one table and one plot

